# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

resources:
  pipelines:
  - pipeline: tech-arti-blogs.pipelines-dotnet-core   # Name of the pipeline resource
    source: azure-pipelines-4.yml # Name of the pipeline referenced by the pipeline resource
    project: Configuring Pipeline # Required only if the source pipeline is in another project
    trigger: true # enable the trigger
  
pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

