# azure-pipelines.yml
name: FirstPipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest
  
steps:
- script: echo This pipeline runs first and will trigger a second pipeline !
- template: 2_azure-pipelines-template.yml
